2021-09-28 10:29:49,104 - INFO - 登录测试
2021-09-28 10:29:49,818 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 10:29:50,448 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 10:29:51,068 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 10:29:51,693 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:03:24,201 - INFO - 登录测试
2021-09-28 13:03:24,864 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:03:25,529 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:03:26,157 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:03:26,785 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:04:14,167 - INFO - 登录测试
2021-09-28 13:04:14,831 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:04:15,489 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:04:16,115 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:04:16,741 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:16:43,014 - INFO - 登录测试
2021-09-28 13:16:43,682 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:16:44,311 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:16:44,936 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:16:45,562 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:19:49,687 - INFO - 登录测试
2021-09-28 13:19:49,862 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:19:50,488 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:19:51,115 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:19:51,743 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:21:37,082 - INFO - 登录测试
2021-09-28 13:21:37,748 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:21:38,382 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:21:39,007 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:21:39,663 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:21:44,099 - INFO - 博客访问测试
2021-09-28 13:21:44,099 - INFO - 博客访问测试
2021-09-28 13:22:56,697 - INFO - 登录测试
2021-09-28 13:22:57,368 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:22:58,026 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:22:58,655 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:22:59,299 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:23:01,401 - INFO - 博客访问测试
2021-09-28 13:23:01,401 - INFO - 博客访问测试
2021-09-28 13:25:03,772 - INFO - 登录测试
2021-09-28 13:25:04,451 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:25:05,077 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:25:05,697 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:25:06,353 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:25:10,734 - INFO - 博客访问测试
2021-09-28 13:25:10,734 - INFO - 博客访问测试
2021-09-28 13:29:02,347 - INFO - 登录测试
2021-09-28 13:29:02,518 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:29:03,145 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:29:03,781 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:29:04,433 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 13:29:08,798 - INFO - 博客访问测试
2021-09-28 13:29:08,798 - INFO - 博客访问测试
2021-09-28 13:29:09,311 - DEBUG - 失败日志
2021-09-28 13:29:09,311 - DEBUG - 失败日志
2021-09-28 14:00:44,298 - INFO - 登录测试
2021-09-28 14:00:44,461 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:00:45,089 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:00:45,720 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:00:46,351 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:00:50,751 - INFO - 博客访问测试
2021-09-28 14:00:50,751 - INFO - 博客访问测试
2021-09-28 14:02:57,069 - INFO - 登录测试
2021-09-28 14:02:57,744 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:02:58,382 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:02:59,006 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:02:59,629 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:03:01,727 - INFO - 博客访问测试
2021-09-28 14:03:01,727 - INFO - 博客访问测试
2021-09-28 14:03:19,429 - INFO - 登录测试
2021-09-28 14:03:19,611 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:03:20,278 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:03:20,906 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:03:21,537 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:03:25,932 - INFO - 博客访问测试
2021-09-28 14:03:25,932 - INFO - 博客访问测试
2021-09-28 14:04:48,073 - INFO - 登录测试
2021-09-28 14:04:48,758 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:04:49,391 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:04:50,019 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:04:50,654 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:04:55,060 - INFO - 博客访问测试
2021-09-28 14:04:55,060 - INFO - 博客访问测试
2021-09-28 14:06:38,826 - INFO - 登录测试
2021-09-28 14:06:39,488 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:06:40,119 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:06:40,743 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:06:41,372 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:06:45,759 - INFO - 博客访问测试
2021-09-28 14:06:45,759 - INFO - 博客访问测试
2021-09-28 14:06:45,770 - DEBUG - 错误
2021-09-28 14:06:45,770 - DEBUG - 错误
2021-09-28 14:09:02,616 - INFO - 登录测试
2021-09-28 14:09:02,799 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:09:03,465 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:09:04,085 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:09:04,717 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:09:09,142 - INFO - 博客访问测试
2021-09-28 14:09:09,142 - INFO - 博客访问测试
2021-09-28 14:09:09,151 - DEBUG - 断言错误，title不一致
2021-09-28 14:09:09,151 - DEBUG - 断言错误，title不一致
2021-09-28 14:23:14,609 - INFO - 登录测试
2021-09-28 14:23:15,288 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:23:15,936 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:23:16,560 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:23:17,193 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:23:21,614 - INFO - 博客访问测试
2021-09-28 14:23:21,614 - INFO - 博客访问测试
2021-09-28 14:46:20,167 - INFO - 登录测试
2021-09-28 14:46:20,864 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:46:21,495 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:46:22,116 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:46:22,745 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:46:27,224 - INFO - 博客访问测试
2021-09-28 14:46:27,224 - INFO - 博客访问测试
2021-09-28 14:46:27,232 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
2021-09-28 14:46:27,232 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
2021-09-28 14:48:34,932 - INFO - 登录测试
2021-09-28 14:48:35,133 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:48:35,320 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:48:35,440 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:48:36,063 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:48:40,371 - INFO - 博客访问测试
2021-09-28 14:48:40,371 - INFO - 博客访问测试
2021-09-28 14:48:40,380 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 14:48:40,380 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 14:51:59,987 - INFO - 登录测试
2021-09-28 14:52:00,160 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:52:00,783 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:52:01,409 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:52:02,034 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:52:06,373 - INFO - 博客访问测试
2021-09-28 14:52:06,373 - INFO - 博客访问测试
2021-09-28 14:52:06,381 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 14:52:06,381 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 14:54:22,099 - INFO - 登录测试
2021-09-28 14:54:22,312 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:54:22,949 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:54:23,580 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:54:24,211 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:54:26,317 - INFO - 博客访问测试
2021-09-28 14:54:26,317 - INFO - 博客访问测试
2021-09-28 14:54:26,326 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 14:54:26,326 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 14:55:11,611 - INFO - 登录测试
2021-09-28 14:55:12,296 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:55:12,936 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:55:13,555 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:55:14,184 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:55:18,553 - INFO - 博客访问测试
2021-09-28 14:55:18,553 - INFO - 博客访问测试
2021-09-28 14:55:18,562 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 14:55:18,562 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 14:58:03,063 - INFO - 登录测试
2021-09-28 14:58:03,304 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:58:03,926 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:58:04,552 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:58:05,191 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:58:07,292 - INFO - 博客访问测试
2021-09-28 14:58:07,292 - INFO - 博客访问测试
2021-09-28 14:58:07,301 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 14:58:07,301 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 14:58:26,067 - INFO - 登录测试
2021-09-28 14:58:26,225 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:58:26,884 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:58:27,518 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:58:28,145 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 14:58:32,519 - INFO - 博客访问测试
2021-09-28 14:58:32,519 - INFO - 博客访问测试
2021-09-28 14:58:32,528 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 14:58:32,528 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:03:44,663 - INFO - 登录测试
2021-09-28 15:03:44,831 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:03:45,483 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:03:46,113 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:03:46,741 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:03:51,130 - INFO - 博客访问测试
2021-09-28 15:03:51,130 - INFO - 博客访问测试
2021-09-28 15:03:51,140 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:03:51,140 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:05:54,802 - INFO - 登录测试
2021-09-28 15:05:55,003 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:05:55,633 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:05:56,257 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:05:56,891 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:06:01,250 - INFO - 博客访问测试
2021-09-28 15:06:01,250 - INFO - 博客访问测试
2021-09-28 15:06:01,259 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:06:01,259 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:06:51,633 - INFO - 登录测试
2021-09-28 15:06:52,341 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:06:52,968 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:06:53,093 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:06:53,722 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:06:58,135 - INFO - 博客访问测试
2021-09-28 15:06:58,135 - INFO - 博客访问测试
2021-09-28 15:06:58,143 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:06:58,143 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:12:31,962 - INFO - 登录测试
2021-09-28 15:12:31,962 - INFO - 登录测试
2021-09-28 15:12:32,131 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:12:32,131 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:12:32,762 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:12:32,762 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:12:32,892 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:12:32,892 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:12:33,516 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:12:33,516 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:12:37,920 - INFO - 博客访问测试
2021-09-28 15:12:37,920 - INFO - 博客访问测试
2021-09-28 15:12:37,920 - INFO - 博客访问测试
2021-09-28 15:12:37,929 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:12:37,929 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:12:37,929 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:12:39,684 - ERROR - 报错信息:无法登录，找不到登录按钮
NoneType: None
2021-09-28 15:12:39,684 - ERROR - 报错信息:无法登录，找不到登录按钮
NoneType: None
2021-09-28 15:12:39,684 - ERROR - 报错信息:无法登录，找不到登录按钮
NoneType: None
2021-09-28 15:21:53,373 - INFO - 登录测试
2021-09-28 15:21:53,373 - INFO - 登录测试
2021-09-28 15:21:54,033 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:21:54,033 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:21:54,671 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:21:54,671 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:21:54,796 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:21:54,796 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:21:55,422 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:21:55,422 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:21:59,932 - INFO - 博客访问测试
2021-09-28 15:21:59,932 - INFO - 博客访问测试
2021-09-28 15:21:59,932 - INFO - 博客访问测试
2021-09-28 15:21:59,941 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:21:59,941 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:21:59,941 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:22:01,346 - INFO - 报错信息:无法登录，找不到登录按钮
2021-09-28 15:22:01,346 - INFO - 报错信息:无法登录，找不到登录按钮
2021-09-28 15:22:01,346 - INFO - 报错信息:无法登录，找不到登录按钮
2021-09-28 15:23:33,471 - INFO - 登录测试
2021-09-28 15:23:33,471 - INFO - 登录测试
2021-09-28 15:23:33,709 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:23:33,709 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:23:34,341 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:23:34,341 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:23:34,456 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:23:34,456 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:23:35,079 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:23:35,079 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:23:37,176 - INFO - 博客访问测试
2021-09-28 15:23:37,176 - INFO - 博客访问测试
2021-09-28 15:23:37,176 - INFO - 博客访问测试
2021-09-28 15:23:37,184 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:23:37,184 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:23:37,184 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:23:38,566 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:23:38,566 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:23:38,566 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:25:50,692 - INFO - 登录测试
2021-09-28 15:25:50,692 - INFO - 登录测试
2021-09-28 15:25:51,401 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:25:51,401 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:25:52,037 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:25:52,037 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:25:52,657 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:25:52,657 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:25:53,287 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:25:53,287 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:25:55,379 - INFO - 博客访问测试
2021-09-28 15:25:55,379 - INFO - 博客访问测试
2021-09-28 15:25:55,379 - INFO - 博客访问测试
2021-09-28 15:25:55,387 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:25:55,387 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:25:55,387 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:25:57,249 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:25:57,249 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:25:57,249 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:27:06,342 - INFO - 登录测试
2021-09-28 15:27:06,342 - INFO - 登录测试
2021-09-28 15:27:07,030 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:27:07,030 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:27:07,668 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:27:07,668 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:27:08,289 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:27:08,289 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:27:08,918 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:27:08,918 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:27:13,267 - INFO - 博客访问测试
2021-09-28 15:27:13,267 - INFO - 博客访问测试
2021-09-28 15:27:13,267 - INFO - 博客访问测试
2021-09-28 15:27:13,277 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:27:13,277 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:27:13,277 - ERROR - 报错信息:报错啦！页面无法访问！
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 118, in test_list
    assert self.driver.title == expected
AssertionError: assert '小不典-Blog' == '小白典-Blog'
  - 小白典-Blog
  ?  ^
  + 小不典-Blog
  ?  ^
2021-09-28 15:27:15,052 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:27:15,052 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:27:15,052 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:28:33,083 - INFO - 登录测试
2021-09-28 15:28:33,083 - INFO - 登录测试
2021-09-28 15:28:33,270 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:28:33,270 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:28:33,945 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:28:33,945 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:28:34,066 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:28:34,066 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:28:34,700 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:28:34,700 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:28:39,169 - INFO - 博客访问测试
2021-09-28 15:28:39,169 - INFO - 博客访问测试
2021-09-28 15:28:39,169 - INFO - 博客访问测试
2021-09-28 15:28:41,514 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:28:41,514 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:28:41,514 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:30:31,235 - INFO - 登录测试
2021-09-28 15:30:31,235 - INFO - 登录测试
2021-09-28 15:30:31,957 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:30:31,957 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:30:32,595 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:30:32,595 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:30:33,224 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:30:33,224 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:30:33,850 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:30:33,850 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:30:38,199 - INFO - 博客访问测试
2021-09-28 15:30:38,199 - INFO - 博客访问测试
2021-09-28 15:30:38,199 - INFO - 博客访问测试
2021-09-28 15:30:40,536 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:30:40,536 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:30:40,536 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 148, in test_baidu
    driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:37:22,341 - INFO - 登录测试
2021-09-28 15:37:22,534 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:37:23,167 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:37:23,294 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:37:23,922 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:37:28,274 - INFO - 博客访问测试
2021-09-28 15:37:28,274 - INFO - 博客访问测试
2021-09-28 15:37:29,952 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 135, in test_baidu
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:37:29,952 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 135, in test_baidu
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 15:53:29,632 - INFO - 登录测试
2021-09-28 15:53:29,800 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:53:30,420 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:53:30,540 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:53:31,166 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 15:53:32,941 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 61, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 20:09:26,336 - INFO - 登录测试
2021-09-28 20:09:27,042 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:09:27,773 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:09:28,486 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:09:29,202 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:09:31,155 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 61, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 20:17:50,119 - INFO - 登录测试
2021-09-28 20:17:50,306 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:17:50,952 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:17:51,603 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:17:52,257 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:17:54,030 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 61, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 20:37:18,153 - INFO - 登录测试
2021-09-28 20:37:18,820 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:37:19,452 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:37:20,083 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:37:20,759 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:37:22,276 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 20:37:59,259 - INFO - 登录测试
2021-09-28 20:37:59,945 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:38:00,575 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:38:01,217 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:38:01,896 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:38:03,554 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 20:42:14,135 - INFO - 登录测试
2021-09-28 20:42:14,814 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:42:15,446 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:42:16,073 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:42:16,757 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:42:18,212 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 20:43:12,541 - INFO - 登录测试
2021-09-28 20:43:13,216 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:43:13,838 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:43:14,459 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:43:15,131 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:46:00,360 - INFO - 登录测试
2021-09-28 20:46:01,055 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:46:01,682 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:46:02,308 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:46:02,991 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:49:40,338 - INFO - 登录测试
2021-09-28 20:49:41,385 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:49:42,103 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:49:42,798 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:49:43,488 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:49:45,718 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\code\selenium\se_project\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 20:55:46,245 - INFO - 登录测试
2021-09-28 20:55:46,931 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:55:47,572 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:55:48,193 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:55:48,877 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:55:50,413 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 20:58:57,291 - INFO - 登录测试
2021-09-28 20:58:57,969 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:58:58,599 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:58:59,220 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 20:58:59,897 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:01:22,950 - INFO - 登录测试
2021-09-28 21:01:23,636 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:01:24,265 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:01:24,885 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:01:25,558 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:01:27,029 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 21:04:17,835 - INFO - 登录测试
2021-09-28 21:04:18,504 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:04:19,133 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:04:19,764 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:04:20,437 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:05:43,666 - INFO - 登录测试
2021-09-28 21:05:44,343 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:05:44,975 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:05:45,599 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:05:46,276 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:08:32,116 - INFO - 登录测试
2021-09-28 21:08:32,902 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:08:33,526 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:08:34,152 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:08:34,832 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:10:18,324 - INFO - 登录测试
2021-09-28 21:10:19,000 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:10:19,641 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:10:20,278 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:10:20,961 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:10:22,510 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 21:11:30,992 - INFO - 登录测试
2021-09-28 21:11:31,675 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:11:32,299 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:11:32,929 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:11:33,611 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:14:04,854 - INFO - 登录测试
2021-09-28 21:14:05,536 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:14:06,168 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:14:06,805 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:14:07,486 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:14:09,134 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 21:23:40,097 - INFO - 登录测试
2021-09-28 21:23:40,803 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:23:41,423 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:23:42,039 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:23:42,716 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:26:16,523 - INFO - 登录测试
2021-09-28 21:26:17,302 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:26:17,936 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:26:18,566 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:26:19,246 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:26:20,703 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 21:27:13,029 - INFO - 登录测试
2021-09-28 21:27:13,709 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:27:14,333 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:27:14,954 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:27:15,633 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:27:17,121 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 21:28:03,867 - INFO - 登录测试
2021-09-28 21:28:04,548 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:28:05,174 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:28:05,797 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:28:06,474 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:28:08,052 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 21:28:54,433 - INFO - 登录测试
2021-09-28 21:28:55,108 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:28:55,731 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:28:56,350 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:28:57,031 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:28:58,496 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 62, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 21:37:21,240 - INFO - 登录测试
2021-09-28 21:37:21,910 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:37:22,538 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:37:23,166 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:37:23,348 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:37:24,781 - ERROR - 报错信息:无法登录，找不到登录按钮
Traceback (most recent call last):
  File "D:\Code\Selenium\SE_project\testcases\Pytest\test_Jpress.py", line 63, in test_failcase
    self.driver.find_element(By.CLASS_NAME, "btn错误的登录按钮元素").click()
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "f:\jetbrains\pycharm\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn错误的登录按钮元素"}
  (Session info: chrome=93.0.4577.63)

2021-09-28 21:43:31,667 - INFO - 登录测试
2021-09-28 21:43:32,342 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:43:32,971 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:43:33,591 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:43:34,275 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:44:51,476 - INFO - 登录测试
2021-09-28 21:44:52,155 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:44:52,787 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:44:53,421 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:44:54,104 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:45:37,880 - INFO - 登录测试
2021-09-28 21:45:38,053 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:45:38,681 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:45:39,302 - DEBUG - 登录失败，用户名或密码输出有误！
2021-09-28 21:45:39,923 - DEBUG - 登录失败，用户名或密码输出有误！
